### ISSUE TITLE
It seems that it can not resolve icons.

### ISSUE THREAD

**Issue by CreateAndInject** [dblock/resourcelib#20]
var file = Path.Combine(Environment.GetFolderPath(Environment.SpecialFolder.Windows), "explorer.exe");

ResourceInfo info = new ResourceInfo();
info.Load(file);
var res= info[Kernel32.ResourceTypes.RT_ICON];//res has so many icons, but their type is GenericResource not IconResource, so I can not save it as .ico file.
            
IconResource icon = new IconResource();
icon.LoadFrom(file);// throw exception

**Comment by thoemmi** [comment]
@CreateAndInject I guess you want to get the **Icon Groups** from `explorer.exe`. Resource-wise an **icon** has a specific size and color depth. An **icon group** is a container for icons, generally combining the same icon in different sizes and/or color depth.
Following code *works on my machine*&trade;
```C#
var file = Path.Combine(Environment.GetFolderPath(Environment.SpecialFolder.Windows), "explorer.exe");

ResourceInfo info = new ResourceInfo();
info.Load(file);
var resources = info[Kernel32.ResourceTypes.RT_GROUP_ICON];
foreach (var resource in resources) 
{
    IconDirectoryResource icon = new IconDirectoryResource();
    icon.Language = resource.Language;
    icon.Name = resource.Name;
    icon.LoadFrom(file);
}
```

**Comment by dblock** [comment]
Lets close this, @CreateAndInject reopen if the above doesn't solve your problem.

**Comment by CreateAndInject** [comment]
var file = Path.Combine(Environment.GetFolderPath(Environment.SpecialFolder.Windows), "explorer.exe");

ResourceInfo info = new ResourceInfo();
info.Load(file);
var resources = info[Kernel32.ResourceTypes.RT_GROUP_ICON];
foreach (var resource in resources) 
{
    IconDirectoryResource icon = new IconDirectoryResource();
    icon.Language = resource.Language;
    icon.Name = resource.Name;
    icon.LoadFrom(file);

   ** icon.Icons[0].SaveIconTo("c:\\a.ico");** //error
}

**Comment by dblock** [comment]
What is the error? Same problem as above?

**Comment by thoemmi** [comment]
I guess #36 is the follow-up.
