### ISSUE TITLE
Can not change version info of exe file

### ISSUE THREAD

**Issue by hungncv** [dblock/resourcelib#30]
Dear all,
When I run sample source on help document to change version infor for a dll file (ex: C:\demo.dll), 
i see that it was changed,
but if change file name to exe file ("C:\demo1.exe"), it could not changed.
Have got anyone tell me why ?
Can Resourcelib be change version infor for exe file ?
Pls help me.

**Comment by dblock** [comment]
Yes, ResourceLib can definitely change resources in executables, so something odd is going on. Often it's a locale problem where the resource in one language is read and another is written or something like that. It could be other things too. I suggest you compare the resources in the before and after versions and see what ResourceLib wrote and what the difference is.

**Comment by hungncv** [comment]
Thank for your answer !
Sorry for my mistake. Executable file did i used to try can be wrong. I replaced other files and they have been changed correctly.

**Comment by dblock** [comment]
I'll close this. If you have a case where the written data is wrong into your executable, do open a bug.

**Comment by hungncv** [comment]
Sorry, could you guide me how to change version information of exe which is created by .NET ( .NET assemblies). I've changed to ResourceUtil.NEUTRALLANGID in my source code but nothing changed.

Regards

**Comment by dblock** [comment]
I don't think there's anything special about .NET assemblies.

**Comment by hungncv** [comment]
Thank you. I found solution for my issue.
