### ISSUE TITLE
Consider batching update operations

### ISSUE THREAD

**Issue by ljani** [dblock/resourcelib#37]
The [current implementation](https://github.com/dblock/resourcelib/blob/e285e68c81a3fbb40e6c0f14fc89bf35a9dc4692/Source/ResourceLib/Resource.cs#L300-L311) seems to call `BeginUpdateResource` and `EndUpdateResource` for each `UpdateResource` call. At least I would prefer the "all-or-nothing" (transactional) approach:

- Call `BeginUpdateResource` once when eg. `ResourceInfo.Save` is called
- Make multiple `UpdateResource` calls
- Call `EndUpdateResource` at the end

The reason for this is that I seem to be getting randomly a `Win32Exception` sometimes in tight loops. (Probably because of the antivirus.) The error message is either:

- `5`: `Access is denied`
- `110`: `The system cannot open the device or file specified`

With the transactional approach I would know I haven't written something partially and left things in an inconsistent state.

[Remarks](https://msdn.microsoft.com/en-us/library/windows/desktop/ms648049(v=vs.85).aspx):

> An application can use UpdateResource repeatedly to make changes to the resource data. Each call to UpdateResource contributes to an internal list of additions, deletions, and replacements but does not actually write the data to the file indicated by hUpdate. The application must use the EndUpdateResource function to write the accumulated changes to the file.

Thanks for the awesome lib!

**Comment by dblock** [comment]
This sounds reasonable.
