### ISSUE TITLE
Unable to build the Wix Extensions

### ISSUE THREAD

**Issue by waqar2012** [dblock/resourcelib#42]
ANy body have any wixExtensions latest dll that are compatible with VS2013. i am unable to build the WixExtenions dll. These are errors that i am getting
>	C:\Users\user\Downloads\msiext-master\msiext-master\externals\wix\candle.exe -dDebug -d"DevEnvDir=C:\Program Files\Microsoft Visual Studio 12.0\Common7\IDE\\" -dSolutionDir=C:\Users\user\Downloads\msiext-master\msiext-master\ -dSolutionExt=.sln -dSolutionFileName=msi.sln -dSolutionName=msi -dSolutionPath=C:\Users\user\Downloads\msiext-master\msiext-master\msi.sln -dConfiguration=Debug -dOutDir=..\..\..\..\target\Debug\bin\ -dPlatform=x86 -dProjectDir=C:\Users\user\Downloads\msiext-master\msiext-master\src\WixExtensions\DataSourceExtension\wixlib\ -dProjectExt=.wixproj -dProjectFileName=DataSourceExtension.wixproj -dProjectName=DataSourceExtension -dProjectPath=C:\Users\user\Downloads\msiext-master\msiext-master\src\WixExtensions\DataSourceExtension\wixlib\DataSourceExtension.wixproj -dTargetDir=C:\Users\user\Downloads\msiext-master\msiext-master\target\Debug\bin\ -dTargetExt=.wixlib -dTargetFileName=DataSource.wixlib -dTargetName=DataSource -dTargetPath=C:\Users\user\Downloads\msiext-master\msiext-master\target\Debug\bin\DataSource.wixlib -out ..\..\..\..\target\Debug\obj\DataSourceExtension\ -pedantic -arch x86 DataSourceExtension.wxs
28>C:\Users\user\Downloads\msiext-master\msiext-master\src\WixExtensions\DataSourceExtension\wixlib\DataSourceExtension.wxs(8,0): warning CNDL1118: The variable 'SolutionDir' with value 'C:\Users\user\Downloads\msiext-master\msiext-master\src\WixExtensions\DataSourceExtension\wixlib\..\..\..\..' was previously declared with value 'C:\Users\user\Downloads\msiext-master\msiext-master\'.
28>	C:\Users\user\Downloads\msiext-master\msiext-master\externals\wix\lit.exe -out C:\Users\user\Downloads\msiext-master\msiext-master\target\Debug\bin\DataSource.wixlib -bf -loc en-US.wxl -pedantic ..\..\..\..\target\Debug\obj\DataSourceExtension\DataSourceExtension.wixobj
28>C:\Users\user\Downloads\msiext-master\msiext-master\src\WixExtensions\DataSourceExtension\wixlib\DataSourceExtension.wxs(69,0): error LIT0103: The system cannot find the file 'C:\Users\user\Downloads\msiext-master\msiext-master\src\WixExtensions\DataSourceExtension\wixlib\..\..\..\..\target\Debug\bin\DataSource.dll' with type 'Binary'.
28>Done building project "DataSourceExtension.wixproj" -- FAILED.
28>
29>------ Rebuild All started: Project: CommonUiExtension (Source\Wix Extensions\CommonUiExtension\CommonUiExtension), Configuration: Debug x86 ------
30>------ Rebuild All started: Project: WixDataSourceExtension, Configuration: Debug Any CPU ------
29>	..\..\..\..\externals\wix\candle.exe -dDebug -d"DevEnvDir=C:\Program Files\Microsoft Visual Studio 12.0\Common7\IDE\\" -dSolutionDir=C:\Users\user\Downloads\msiext-master\msiext-master\ -dSolutionExt=.sln -dSolutionFileName=msi.sln -dSolutionName=msi -dSolutionPath=C:\Users\user\Downloads\msiext-master\msiext-master\msi.sln -dConfiguration=Debug -dOutDir=..\..\..\..\target\Debug\bin\ -dPlatform=x86 -dProjectDir=C:\Users\user\Downloads\msiext-master\msiext-master\src\WixExtensions\CommonUiExtension\wixlib\ -dProjectExt=.wixproj -dProjectFileName=CommonUiExtension.wixproj -dProjectName=CommonUiExtension -dProjectPath=C:\Users\user\Downloads\msiext-master\msiext-master\src\WixExtensions\CommonUiExtension\wixlib\CommonUiExtension.wixproj -dTargetDir=C:\Users\user\Downloads\msiext-master\msiext-master\target\Debug\bin\ -dTargetExt=.wixlib -dTargetFileName=CommonUi.wixlib -dTargetName=CommonUi -dTargetPath=C:\Users\user\Downloads\msiext-master\msiext-master\target\Debug\bin\CommonUi.wixlib -out ..\..\..\..\target\Debug\obj\CommonUiExtension\ -pedantic -arch x86 -ext ..\..\..\..\externals\wix\WixUIExtension.dll Common.wxs GenericErrorDlg.wxs RuntimeDbCredDlg.wxs ServiceCredDlg.wxs ServicePortDlg.wxs DbCreateCredDlg.wxs SelectDbDlg.wxs
29>C:\Users\user\Downloads\msiext-master\msiext-master\src\WixExtensions\CommonUiExtension\wixlib\Common.wxs(8,0): warning CNDL1118: The variable 'SolutionDir' with value 'C:\Users\user\Downloads\msiext-master\msiext-master\src\WixExtensions\CommonUiExtension\wixlib\..\..\..\..' was previously declared with value 'C:\Users\user\Downloads\msiext-master\msiext-master\'.
29>	..\..\..\..\externals\wix\lit.exe -out C:\Users\user\Downloads\msiext-master\msiext-master\target\Debug\bin\CommonUi.wixlib -bf -ext ..\..\..\..\externals\wix\WixUIExtension.dll -loc en-US.wxl -pedantic ..\..\..\..\target\Debug\obj\CommonUiExtension\Common.wixobj ..\..\..\..\target\Debug\obj\CommonUiExtension\GenericErrorDlg.wixobj ..\..\..\..\target\Debug\obj\CommonUiExtension\RuntimeDbCredDlg.wixobj ..\..\..\..\target\Debug\obj\CommonUiExtension\ServiceCredDlg.wixobj ..\..\..\..\target\Debug\obj\CommonUiExtension\ServicePortDlg.wixobj ..\..\..\..\target\Debug\obj\CommonUiExtension\DbCreateCredDlg.wixobj ..\..\..\..\target\Debug\obj\CommonUiExtension\SelectDbDlg.wixobj
29>C:\Users\user\Downloads\msiext-master\msiext-master\src\WixExtensions\CommonUiExtension\wixlib\Common.wxs(43,0): error LIT0103: The system cannot find the file 'C:\Users\user\Downloads\msiext-master\msiext-master\src\WixExtensions\CommonUiExtension\wixlib\..\..\..\..\target\Debug\bin\StringTools.dll' with type 'Binary'.
30>CSC : error CS1566: Error reading resource file 'c:\Users\user\Downloads\msiext-master\msiext-master\target\Debug\bin\DataSource.wixlib' -- 'The system cannot find the file specified. '
31>------ Rebuild All started: Project: WixCommonUiExtension, Configuration: Debug Any CPU ------
31>CSC : error CS1566: Error reading resource file 'c:\Users\user\Downloads\msiext-master\msiext-master\target\Debug\bin\CommonUi.wixlib' -- 'The system cannot find the file specified. '

**Comment by dblock** [comment]
This is the resourcelib project, what does it have to do with wix extensions?

**Comment by dblock** [comment]
Did you mean to open this in https://github.com/dblock/msiext?

**Comment by waqar2012** [comment]
Yes

**Comment by waqar2012** [comment]
I want to implement the database gui to load the servers in drop down list and its windows or sql authenticate 
Regards 
Waqar

**Comment by thoemmi** [comment]
@waqar2012 This is the wrong repository! Go to https://github.com/dblock/msiext/issues and open an issue there.
