### ISSUE TITLE
Issue when saving changed version strings

### ISSUE THREAD

**Issue by LennartAJansson** [dblock/resourcelib#43]
I have a very simple scenario:
I have an exe that we are using for several environments, it's deployed with ClickOnce and due to that we need to make them unique so we could run several instances of the same application on one single client. So, I have a renamed exe and I need to rename the version strings too, I try following:

```
static void Main(string[] args)
{
      //The filename is originally LexecutorClient.exe
      //We rename it for each environment, in this case QA
      string filename = "Test\\LexecutorClient.QA.exe";
      string newFileString = Path.GetFileName(filename);
      string newProductString = Path.GetFileNameWithoutExtension(filename);

      VersionResource vr = new VersionResource();
      vr.LoadFrom(filename);

      StringFileInfo stringFileInfo = (StringFileInfo)vr["StringFileInfo"];

      Console.WriteLine("Old FileDescription: {0}", stringFileInfo["FileDescription"]);
      Console.WriteLine("Old InternalName: {0}", stringFileInfo["InternalName"]);
      Console.WriteLine("Old OriginalFilename: {0}", stringFileInfo["OriginalFilename"]);
      Console.WriteLine("Old ProductName: {0}", stringFileInfo["ProductName"]);

      stringFileInfo["FileDescription"] = newProductString;
      stringFileInfo["InternalName"] = newFileString;
      stringFileInfo["OriginalFilename"] = newFileString;
      stringFileInfo["ProductName"] = newProductString;

      vr.SaveTo(filename);
}

```
When I try to read the change with ResourceLib it shows my changes ok, but when I use file properties in the system it shows the same values as before and in ResEdit it looks like the attached images. What is wrong here? As you can see there's now two Version Information nodes, one Neutral with the old information untouched and a new English US with the changed information...

![after1](https://cloud.githubusercontent.com/assets/16935455/17215474/41b2bb40-54dd-11e6-8851-8c5161536e6a.jpg)
![after2](https://cloud.githubusercontent.com/assets/16935455/17215472/41aff2f2-54dd-11e6-9fe7-c9893cdf9b9d.jpg)
![before](https://cloud.githubusercontent.com/assets/16935455/17215473/41b28fee-54dd-11e6-8292-b3dddd017452.jpg)

**Comment by thoemmi** [comment]
The default language for new `VersionResource` instances is [English](https://github.com/dblock/resourcelib/blob/master/Source/ResourceLib/VersionResource.cs#L66). When you call `LoadFrom`, Windows cannot find an English versioninfo, so it falls back to the default Neutral.  In other words, you've loaded the neutral versioninfo, patched it, and saved it as English.

Add `vr.Language = 0` to your code, and it should work as expected. Can you confirm this?

**Comment by LennartAJansson** [comment]
Works like a charm! Good to know that I need to handle that manually, thanks a lot :)
