### ISSUE TITLE
Cant get string resources

### ISSUE THREAD

**Issue by HassanNiazi** [dblock/resourcelib#49]
Cannot get string resources which are located in the resource files. Only resources returned are the Manifest and Version. If we use the RT_String for getting specifically string resources we get no matching key in the dictionary.

**Comment by dblock** [comment]
You should be able to debug this or at least post something with a repro here (test + binary).

**Comment by HassanNiazi** [comment]
Sure will get back with it.

**Comment by HassanNiazi** [comment]
Hi,
Following is the code and the response. I am also uploading the projects repos and will send link in comments.


 `   
   using (ResourceInfo ri = new ResourceInfo())
            {
                ri.Load(filename);
             
              // I get following error at the  ri[Kernel32.ResourceTypes.RT_STRING] because there is no 
              // String resources extracted from the executable.
              // An unhandled exception of type 'System.Collections.Generic.KeyNotFoundException
              //occurred in mscorlib.dll
              //Additional information: The given key was not present in the dictionary.
              
               foreach (StringResource rc in ri[Kernel32.ResourceTypes.RT_STRING])
                {
                    Console.WriteLine("StringResource: {0}, {1}", rc.Name, rc.TypeName);
                    Console.WriteLine(rc);
                }
            } 
`

**Comment by HassanNiazi** [comment]
Hi Following are the links to the sample repos.

Project with the Resource file which we aim to extract.
https://github.com/HassanNiazi/ResourceLibSampleDataProject

Project with the ResourceLib code which should extract the resource file
https://github.com/HassanNiazi/ResourceLibSampleDataExtractionProject

**Comment by dblock** [comment]
Thanks. Just to set expectations I haven't done much windows development for a long time, so I am not going to be debugging this. I am happy to help with any advice though ;)

**Comment by thoemmi** [comment]
@HassanNiazi The `ConsoleApplication2` in the `ResourceLibSampleDataProject` repository doesn't contain any **Win32 resources** but **embedded .NET resources.** `resourcelib`'s scope is Win32 resources however.

For accessing embedded resources I recommend to use .NET's [ResourceManager](https://msdn.microsoft.com/en-us/library/system.resources.resourcemanager(v=vs.110).aspx).

**Comment by dblock** [comment]
Thanks for checking it out @thoemmi!

**Comment by HassanNiazi** [comment]
Thanks @thoemmi  :)
